from sqlalchemy.orm import Session
from ..models import User, Vehicle, Destination, Shipment, DeliveryHistory, Pool, DeliveryOutcome
from ..auth import get_password_hash

def seed_database_if_empty(db: Session):
    # Check if demo users exist; seed if missing
    if db.query(User).count() == 0:
        print("Seeding demo user accounts into SQLite database...")
        demo_users = [
            User(
                id="USR-ADMIN-01",
                email="admin@routenova.com",
                hashed_password=get_password_hash("admin123"),
                full_name="System Admin",
                role="ADMIN",
                is_active=True
            ),
            User(
                id="USR-FLEET-01",
                email="fleet@routenova.com",
                hashed_password=get_password_hash("fleet123"),
                full_name="Fleet Operations Manager",
                role="FLEET_MANAGER",
                is_active=True
            ),
            User(
                id="USR-DISPATCH-01",
                email="dispatcher@routenova.com",
                hashed_password=get_password_hash("dispatch123"),
                full_name="Logistics Dispatcher",
                role="DISPATCHER",
                is_active=True
            ),
            User(
                id="USR-DRIVER-01",
                email="driver@routenova.com",
                hashed_password=get_password_hash("driver123"),
                full_name="K. Ramesh (Driver)",
                role="DRIVER",
                is_active=True
            ),
            User(
                id="USR-SHIPPER-01",
                email="shipper@routenova.com",
                hashed_password=get_password_hash("shipper123"),
                full_name="Agricultural Co-op Shipper",
                role="DISPATCHER",
                is_active=True
            ),
        ]
        for u in demo_users:
            db.add(u)
        db.commit()

    # Check if vehicles already seeded
    if db.query(Vehicle).count() > 0:
        return

    _seed_all_demo_data(db)

def reset_demo_database(db: Session):
    """
    Restores database to known clean demonstration state.
    Deletes dispatches, pool_shipments, pools, delivery_outcomes, delivery_history, shipments, vehicles, destinations.
    Preserves user accounts.
    """
    from ..models import Dispatch, PoolShipment, Pool, DeliveryOutcome, DeliveryHistory, Shipment, Vehicle, Destination

    db.query(Dispatch).delete()
    db.query(PoolShipment).delete()
    db.query(Pool).delete()
    db.query(DeliveryOutcome).delete()
    db.query(DeliveryHistory).delete()
    db.query(Shipment).delete()
    db.query(Vehicle).delete()
    db.query(Destination).delete()
    db.commit()

    _seed_all_demo_data(db)

def _seed_all_demo_data(db: Session):



    # 2. Destinations
    destinations_data = [
        {
            "id": "DEST-RAMPURAM",
            "name": "Rampuram Village",
            "district": "Green Valley District",
            "latitude": 18.2949,
            "longitude": 83.8938,
            "road_access_score": 35,
            "address_confidence_score": 70,
            "connectivity_score": 78,
            "historical_success_rate": 62,
            "final_segment_distance": 2.1,
            "road_surface": "mixed",
            "road_width_category": "narrow",
            "local_evidence": "Sector 4 track flooded during morning dew; bridge weight limit 3.5T. 2WD van axle stuck recorded 2 days ago.",
            "risk_notes": "High mud rutting risk for 2WD vans. Recommend 4x4 drivetrain or micropooling on mini truck.",
            "prototype_risk_level": "HIGH",
            "default_landmark": "Panchayati Well, Sector 4",
        },
        {
            "id": "DEST-KOTHURU",
            "name": "Kothuru Village",
            "district": "North Corridor Zone B",
            "latitude": 18.3412,
            "longitude": 83.9215,
            "road_access_score": 75,
            "address_confidence_score": 90,
            "connectivity_score": 60,
            "historical_success_rate": 88,
            "final_segment_distance": 1.2,
            "road_surface": "paved_asphalt",
            "road_width_category": "standard",
            "local_evidence": "Paved state highway until 1km clinic approach. Alleyway width 2.4m.",
            "risk_notes": "Cellular drop near valley pass. EV 3-Wheeler or Mini Truck compatible.",
            "prototype_risk_level": "MEDIUM",
            "default_landmark": "Primary Health Clinic",
        },
        {
            "id": "DEST-GARIVIDI",
            "name": "Garividi Industrial Ridge",
            "district": "Garividi Industrial District",
            "latitude": 18.2511,
            "longitude": 83.8410,
            "road_access_score": 92,
            "address_confidence_score": 95,
            "connectivity_score": 95,
            "historical_success_rate": 98,
            "final_segment_distance": 0.5,
            "road_surface": "paved_asphalt",
            "road_width_category": "wide",
            "local_evidence": "Wide asphalt double-lane access to Industrial Gate 2.",
            "risk_notes": "Clear track. Baseline 2WD vans perform with 98% on-time reliability.",
            "prototype_risk_level": "LOW",
            "default_landmark": "Substation 3 Gate 2",
        },
        {
            "id": "DEST-PATHAPATNAM",
            "name": "Pathapatnam Valley",
            "district": "Green Valley District",
            "latitude": 18.3105,
            "longitude": 83.9012,
            "road_access_score": 58,
            "address_confidence_score": 82,
            "connectivity_score": 52,
            "historical_success_rate": 74,
            "final_segment_distance": 3.4,
            "road_surface": "gravel_track",
            "road_width_category": "narrow",
            "local_evidence": "Gravel road along riverbank corridor. Shared route with Rampuram Sector 4 access track.",
            "risk_notes": "Compatible micropooling corridor candidate with Rampuram produce shipments.",
            "prototype_risk_level": "MEDIUM",
            "default_landmark": "Main Junction Hardware Store",
        },
        {
            "id": "DEST-SALUR",
            "name": "Salur Hill Pass",
            "district": "North Corridor Zone B",
            "latitude": 18.2104,
            "longitude": 83.7915,
            "road_access_score": 42,
            "address_confidence_score": 65,
            "connectivity_score": 40,
            "historical_success_rate": 68,
            "final_segment_distance": 4.8,
            "road_surface": "unpaved_mud",
            "road_width_category": "narrow",
            "local_evidence": "Steep 18% slope hill track crossing wooden stream bridge. Monsoon mud swelling.",
            "risk_notes": "Gradient & mud require 4x4 high ground clearance vehicle.",
            "prototype_risk_level": "HIGH",
            "default_landmark": "Salur Ridge Organic Farm Gate",
        },
        {
            "id": "DEST-CHIPURUPALLE",
            "name": "Chipurupalle Agri-Hub",
            "district": "Central Plains District",
            "latitude": 18.3015,
            "longitude": 83.5689,
            "road_access_score": 80,
            "address_confidence_score": 88,
            "connectivity_score": 85,
            "historical_success_rate": 92,
            "final_segment_distance": 1.8,
            "road_surface": "paved_asphalt",
            "road_width_category": "standard",
            "local_evidence": "Clear asphalt access road leading to APMC Market Yard.",
            "risk_notes": "Moderate traffic during morning harvest hours.",
            "prototype_risk_level": "LOW",
            "default_landmark": "APMC Market Yard Gate 1",
        },
        {
            "id": "DEST-VEEPANGANDLA",
            "name": "Veepangandla Remote Settlement",
            "district": "Southern Border Zone",
            "latitude": 18.1402,
            "longitude": 83.4210,
            "road_access_score": 28,
            "address_confidence_score": 45,
            "connectivity_score": 20,
            "historical_success_rate": 52,
            "final_segment_distance": 6.2,
            "road_surface": "unpaved_mud",
            "road_width_category": "narrow",
            "local_evidence": "6.2km unpaved forest track. Zero cellular signal coverage for 4.5km.",
            "risk_notes": "Offline navigation cache mandatory. Severe mud rutting after rainfall.",
            "prototype_risk_level": "HIGH",
            "default_landmark": "Forest Checkpost Well",
        },
        {
            "id": "DEST-BADANGI",
            "name": "Badangi Dairy Co-op",
            "district": "Central Plains District",
            "latitude": 18.3890,
            "longitude": 83.6702,
            "road_access_score": 68,
            "address_confidence_score": 78,
            "connectivity_score": 72,
            "historical_success_rate": 84,
            "final_segment_distance": 2.5,
            "road_surface": "mixed",
            "road_width_category": "standard",
            "local_evidence": "Mixed asphalt and compacted gravel approach to dairy chilling plant.",
            "risk_notes": "Standard van or EV 3-wheeler compatible.",
            "prototype_risk_level": "LOW",
            "default_landmark": "Chilling Plant Dock B",
        },
    ]

    for d in destinations_data:
        db.add(Destination(**d))

    # 3. Vehicles
    vehicles_data = [
        {
            "id": "VEH-MOTO-01",
            "type": "motorcycle",
            "name": "Hero Cargo Moto 150",
            "plate": "AP-31-MC-1011",
            "capacity_kg": 80,
            "base_cost": 25,
            "cost_per_km": 1.2,
            "ground_clearance_mm": 165,
            "drivetrain": "Chain Drive Single",
            "road_compatibility": {"paved_asphalt": 95, "mixed": 85, "gravel_track": 78, "unpaved_mud": 40},
            "rural_suitability": 72,
            "availability": "AVAILABLE",
            "current_load_kg": 0,
            "current_location": "Green Valley Central Depot",
            "assigned_driver": "K. Appala Naidu",
        },
        {
            "id": "VEH-MOTO-02",
            "type": "motorcycle",
            "name": "TVS Heavy Duty XL Cargo",
            "plate": "AP-31-MC-2044",
            "capacity_kg": 110,
            "base_cost": 28,
            "cost_per_km": 1.4,
            "ground_clearance_mm": 175,
            "drivetrain": "Chain Drive Heavy",
            "road_compatibility": {"paved_asphalt": 92, "mixed": 88, "gravel_track": 80, "unpaved_mud": 52},
            "rural_suitability": 78,
            "availability": "AVAILABLE",
            "current_load_kg": 0,
            "current_location": "Kothuru Health Depot",
            "assigned_driver": "B. Raju",
        },
        {
            "id": "VEH-MOTO-03",
            "type": "motorcycle",
            "name": "Yezdi Adventure Rural Express",
            "plate": "AP-31-MC-3088",
            "capacity_kg": 95,
            "base_cost": 35,
            "cost_per_km": 1.8,
            "ground_clearance_mm": 210,
            "drivetrain": "Mono-shock Off-road",
            "road_compatibility": {"paved_asphalt": 90, "mixed": 92, "gravel_track": 90, "unpaved_mud": 75},
            "rural_suitability": 88,
            "availability": "ON_DELIVERY",
            "current_load_kg": 45,
            "current_location": "En route to Kothuru",
            "assigned_driver": "P. Tarun",
        },
        {
            "id": "VEH-MINI-01",
            "type": "mini_truck",
            "name": "Tata Ace Gold 4x4 Mini Truck",
            "plate": "AP-31-TX-9012",
            "capacity_kg": 1200,
            "base_cost": 85,
            "cost_per_km": 3.5,
            "ground_clearance_mm": 220,
            "drivetrain": "4WD Low Range",
            "road_compatibility": {"paved_asphalt": 94, "mixed": 95, "gravel_track": 92, "unpaved_mud": 90},
            "rural_suitability": 96,
            "availability": "AVAILABLE",
            "current_load_kg": 0,
            "current_location": "Green Valley Central Depot",
            "assigned_driver": "Ramesh Babu",
        },
        {
            "id": "VEH-MINI-02",
            "type": "mini_truck",
            "name": "Mahindra Supro Mini Truck",
            "plate": "AP-31-TX-4402",
            "capacity_kg": 1000,
            "base_cost": 75,
            "cost_per_km": 3.1,
            "ground_clearance_mm": 195,
            "drivetrain": "2WD Rear Heavy",
            "road_compatibility": {"paved_asphalt": 95, "mixed": 85, "gravel_track": 78, "unpaved_mud": 60},
            "rural_suitability": 82,
            "availability": "AVAILABLE",
            "current_load_kg": 0,
            "current_location": "Chipurupalle Market Yard",
            "assigned_driver": "T. Venkat",
        },
        {
            "id": "VEH-MINI-03",
            "type": "mini_truck",
            "name": "Ashok Leyland Dost 4x4",
            "plate": "AP-31-TX-7719",
            "capacity_kg": 1350,
            "base_cost": 95,
            "cost_per_km": 3.8,
            "ground_clearance_mm": 230,
            "drivetrain": "4WD Dual Diff Lock",
            "road_compatibility": {"paved_asphalt": 92, "mixed": 94, "gravel_track": 94, "unpaved_mud": 92},
            "rural_suitability": 98,
            "availability": "ON_DELIVERY",
            "current_load_kg": 550,
            "current_location": "En route to Rampuram",
            "assigned_driver": "G. Srinivasa Rao",
        },
        {
            "id": "VEH-VAN-01",
            "type": "van",
            "name": "Standard Delivery Van 2WD",
            "plate": "AP-31-VN-3301",
            "capacity_kg": 850,
            "base_cost": 65,
            "cost_per_km": 2.8,
            "ground_clearance_mm": 140,
            "drivetrain": "2WD Front",
            "road_compatibility": {"paved_asphalt": 98, "mixed": 65, "gravel_track": 55, "unpaved_mud": 28},
            "rural_suitability": 58,
            "availability": "AVAILABLE",
            "current_load_kg": 0,
            "current_location": "District Logistics Hub",
            "assigned_driver": "Suresh Kumar",
        },
        {
            "id": "VEH-VAN-02",
            "type": "van",
            "name": "Maruti Eeco Cargo Van",
            "plate": "AP-31-VN-5520",
            "capacity_kg": 600,
            "base_cost": 55,
            "cost_per_km": 2.4,
            "ground_clearance_mm": 155,
            "drivetrain": "2WD Rear",
            "road_compatibility": {"paved_asphalt": 96, "mixed": 70, "gravel_track": 60, "unpaved_mud": 35},
            "rural_suitability": 64,
            "availability": "AVAILABLE",
            "current_load_kg": 0,
            "current_location": "Garividi Substation Hub",
            "assigned_driver": "M. Somesh",
        },
        {
            "id": "VEH-VAN-03",
            "type": "van",
            "name": "Force Traveller Cargo Van",
            "plate": "AP-31-VN-8811",
            "capacity_kg": 1500,
            "base_cost": 110,
            "cost_per_km": 4.2,
            "ground_clearance_mm": 180,
            "drivetrain": "2WD Heavy Dual Wheel",
            "road_compatibility": {"paved_asphalt": 95, "mixed": 75, "gravel_track": 65, "unpaved_mud": 42},
            "rural_suitability": 70,
            "availability": "MAINTENANCE",
            "current_load_kg": 0,
            "current_location": "Depot Workshop",
            "assigned_driver": "K. Nagesh",
        },
        {
            "id": "VEH-PKP-01",
            "type": "pickup",
            "name": "Mahindra Bolero Camper 4x4",
            "plate": "AP-31-PK-1109",
            "capacity_kg": 1500,
            "base_cost": 115,
            "cost_per_km": 4.0,
            "ground_clearance_mm": 240,
            "drivetrain": "4WD Heavy Duty",
            "road_compatibility": {"paved_asphalt": 90, "mixed": 96, "gravel_track": 98, "unpaved_mud": 96},
            "rural_suitability": 99,
            "availability": "AVAILABLE",
            "current_load_kg": 0,
            "current_location": "Salur Ridge Depot",
            "assigned_driver": "V. Somesh",
        },
        {
            "id": "VEH-PKP-02",
            "type": "pickup",
            "name": "Isuzu D-Max V-Cross 4x4",
            "plate": "AP-31-PK-6603",
            "capacity_kg": 1200,
            "base_cost": 125,
            "cost_per_km": 4.5,
            "ground_clearance_mm": 235,
            "drivetrain": "4WD Shift-on-Fly",
            "road_compatibility": {"paved_asphalt": 94, "mixed": 95, "gravel_track": 96, "unpaved_mud": 94},
            "rural_suitability": 97,
            "availability": "AVAILABLE",
            "current_load_kg": 0,
            "current_location": "Veepangandla Forest Post",
            "assigned_driver": "A. Prasad",
        },
    ]

    for v in vehicles_data:
        db.add(Vehicle(**v))

    # 4. Shipments
    shipments_data = [
        {
            "id": "RN-2026-8801",
            "sender": "Rampuram Farmers Co-op",
            "destination": "Rampuram Village Hub, Sector 4",
            "destination_id": "DEST-RAMPURAM",
            "weight": 240,
            "volume_m3": 1.4,
            "category": "Agricultural Produce & Seeds",
            "priority": "High",
            "delivery_window": "08:00 - 12:00 IST",
            "status": "PRE_DISPATCH_EVALUATION",
            "risk_level": "HIGH",
            "failure_probability": 0.78,
            "conventional_vehicle": "Standard Delivery Van 2WD",
            "recommended_vehicle": "4x4 Rural Mini Truck (Pooled)",
            "created_at": "2026-09-14 06:30",
        },
        {
            "id": "RN-2026-8802",
            "sender": "District Health Logistics Dept",
            "destination": "Kothuru Primary Health Clinic",
            "destination_id": "DEST-KOTHURU",
            "weight": 45,
            "volume_m3": 0.3,
            "category": "Emergency Medical Supplies",
            "priority": "Urgent/Critical",
            "delivery_window": "07:00 - 10:00 IST",
            "status": "DISPATCHED",
            "risk_level": "MEDIUM",
            "failure_probability": 0.34,
            "conventional_vehicle": "Electric 3-Wheeler Heavy",
            "recommended_vehicle": "Electric 3-Wheeler Heavy",
            "created_at": "2026-09-14 07:00",
        },
        {
            "id": "RN-2026-8803",
            "sender": "Micro-Solar Components Ltd",
            "destination": "Garividi Substation 3",
            "destination_id": "DEST-GARIVIDI",
            "weight": 120,
            "volume_m3": 0.8,
            "category": "Solar & Electrical Equipment",
            "priority": "Standard",
            "delivery_window": "09:00 - 17:00 IST",
            "status": "PRE_DISPATCH_EVALUATION",
            "risk_level": "LOW",
            "failure_probability": 0.08,
            "conventional_vehicle": "Standard Delivery Van 2WD",
            "recommended_vehicle": "Standard Delivery Van 2WD",
            "created_at": "2026-09-14 07:15",
        },
        {
            "id": "RN-2026-8804",
            "sender": "Pathapatnam Hardware Store",
            "destination": "Pathapatnam Main Junction",
            "destination_id": "DEST-PATHAPATNAM",
            "weight": 310,
            "volume_m3": 2.1,
            "category": "General Machinery Supplies",
            "priority": "Standard",
            "delivery_window": "08:30 - 12:30 IST",
            "status": "POOL_MATCHED",
            "risk_level": "MEDIUM",
            "failure_probability": 0.28,
            "conventional_vehicle": "Tata Ace Gold 4x4 Mini Truck",
            "recommended_vehicle": "Tata Ace Gold 4x4 Mini Truck (Pooled with RN-2026-8801)",
            "created_at": "2026-09-14 07:20",
        },
        {
            "id": "RN-2026-8805",
            "sender": "Salur Organic Collective",
            "destination": "Salur Ridge Organic Farm Gate",
            "destination_id": "DEST-SALUR",
            "weight": 180,
            "volume_m3": 1.1,
            "category": "Agricultural Produce & Seeds",
            "priority": "High",
            "delivery_window": "10:00 - 14:00 IST",
            "status": "PRE_DISPATCH_EVALUATION",
            "risk_level": "HIGH",
            "failure_probability": 0.72,
            "conventional_vehicle": "Standard Delivery Van 2WD",
            "recommended_vehicle": "Mahindra Bolero Camper 4x4",
            "created_at": "2026-09-14 07:30",
        },
        {
            "id": "RN-2026-8806",
            "sender": "APMC Seed Warehouse",
            "destination": "Chipurupalle APMC Market Yard",
            "destination_id": "DEST-CHIPURUPALLE",
            "weight": 450,
            "volume_m3": 2.8,
            "category": "Agricultural Produce & Seeds",
            "priority": "Standard",
            "delivery_window": "08:00 - 15:00 IST",
            "status": "PRE_DISPATCH_EVALUATION",
            "risk_level": "LOW",
            "failure_probability": 0.12,
            "conventional_vehicle": "Mahindra Supro Mini Truck",
            "recommended_vehicle": "Mahindra Supro Mini Truck",
            "created_at": "2026-09-14 07:35",
        },
        {
            "id": "RN-2026-8807",
            "sender": "Forest Welfare Board",
            "destination": "Veepangandla Forest Post",
            "destination_id": "DEST-VEEPANGANDLA",
            "weight": 85,
            "volume_m3": 0.6,
            "category": "Emergency Medical Supplies",
            "priority": "Urgent/Critical",
            "delivery_window": "06:00 - 11:00 IST",
            "status": "PRE_DISPATCH_EVALUATION",
            "risk_level": "HIGH",
            "failure_probability": 0.84,
            "conventional_vehicle": "Standard Delivery Van 2WD",
            "recommended_vehicle": "Isuzu D-Max V-Cross 4x4",
            "created_at": "2026-09-14 07:40",
        },
        {
            "id": "RN-2026-8808",
            "sender": "Green Valley Fertilizer Depot",
            "destination": "Rampuram Village Hub, Sector 4",
            "destination_id": "DEST-RAMPURAM",
            "weight": 320,
            "volume_m3": 1.8,
            "category": "Agricultural Produce & Seeds",
            "priority": "Standard",
            "delivery_window": "08:30 - 12:30 IST",
            "status": "POOL_MATCHED",
            "risk_level": "HIGH",
            "failure_probability": 0.75,
            "conventional_vehicle": "Standard Delivery Van 2WD",
            "recommended_vehicle": "Ashok Leyland Dost 4x4 (Pooled)",
            "created_at": "2026-09-14 07:45",
        },
        {
            "id": "RN-2026-8809",
            "sender": "Badangi Dairy Co-op",
            "destination": "Badangi Chilling Plant Dock B",
            "destination_id": "DEST-BADANGI",
            "weight": 220,
            "volume_m3": 1.2,
            "category": "Agricultural Produce & Seeds",
            "priority": "High",
            "delivery_window": "09:00 - 13:00 IST",
            "status": "DISPATCHED",
            "risk_level": "LOW",
            "failure_probability": 0.14,
            "conventional_vehicle": "Maruti Eeco Cargo Van",
            "recommended_vehicle": "Maruti Eeco Cargo Van",
            "created_at": "2026-09-14 07:50",
        },
        {
            "id": "RN-2026-8810",
            "sender": "Kothuru School Supplies",
            "destination": "Kothuru Primary School",
            "destination_id": "DEST-KOTHURU",
            "weight": 70,
            "volume_m3": 0.4,
            "category": "General Machinery Supplies",
            "priority": "Low",
            "delivery_window": "10:00 - 16:00 IST",
            "status": "PRE_DISPATCH_EVALUATION",
            "risk_level": "MEDIUM",
            "failure_probability": 0.30,
            "conventional_vehicle": "Hero Cargo Moto 150",
            "recommended_vehicle": "TVS Heavy Duty XL Cargo",
            "created_at": "2026-09-14 07:55",
        },
    ]

    for s in shipments_data:
        db.add(Shipment(**s))

    # 5. Delivery History & Outcomes
    history_data = [
        {
            "id": "OUT-901",
            "shipment_id": "RN-2026-8811",
            "destination_id": "DEST-GARIVIDI",
            "vehicle_id": "VEH-VAN-01",
            "outcome": "SUCCESS",
            "failure_reason": None,
            "delivery_time": "42 mins",
            "cost": 45.0,
            "timestamp": "2026-09-13 14:45",
            "location": "Garividi Substation 3",
            "driver_notes": "Clean asphalt transit. Delivered 15 mins ahead of schedule.",
            "evidence_tagged": "Segment #GAR-01 verified paved asphalt.",
        },
        {
            "id": "OUT-900",
            "shipment_id": "RN-2026-8785",
            "destination_id": "DEST-RAMPURAM",
            "vehicle_id": "VEH-VAN-01",
            "outcome": "FAILURE_REATTEMPT",
            "failure_reason": "Vehicle Stuck in Mud Track (2WD Ground Clearance Mismatch)",
            "delivery_time": "N/A (Towed)",
            "cost": 420.0,
            "timestamp": "2026-09-12 09:30",
            "location": "Rampuram Sector 4 Track",
            "driver_notes": "2WD Van stuck in 18cm unpaved mud rut following unpredicted morning shower. Local tractor towing required.",
            "evidence_tagged": "Segment #RAM-04 tagged with monsoon mud risk & 2WD restriction.",
        },
        {
            "id": "OUT-899",
            "shipment_id": "RN-2026-8774",
            "destination_id": "DEST-KOTHURU",
            "vehicle_id": "VEH-MOTO-03",
            "outcome": "SUCCESS",
            "failure_reason": None,
            "delivery_time": "28 mins",
            "cost": 32.0,
            "timestamp": "2026-09-10 08:15",
            "location": "Kothuru Primary Health Clinic",
            "driver_notes": "Off-road motorcycle easily navigated clinic alleyway entrance.",
            "evidence_tagged": "Cellular signal drop confirmed at km 8.4; offline navigation cache worked perfectly.",
        },
        {
            "id": "OUT-898",
            "shipment_id": "RN-2026-8760",
            "destination_id": "DEST-SALUR",
            "vehicle_id": "VEH-VAN-02",
            "outcome": "FAILURE_REATTEMPT",
            "failure_reason": "Bridge Weight Cap Exceeded & Steep Slope Stall",
            "delivery_time": "N/A (Turned Back)",
            "cost": 280.0,
            "timestamp": "2026-09-08 11:20",
            "location": "Salur Stream Wooden Bridge",
            "driver_notes": "Vehicle payload exceeded wooden bridge 3.5T safety rating. Driver turned back to depot.",
            "evidence_tagged": "Segment #SAL-02 weight limit flagged in database.",
        },
    ]

    for h in history_data:
        db.add(DeliveryHistory(**h))
        db.add(DeliveryOutcome(
            id=h["id"],
            delivery_id=h["shipment_id"],
            destination_id=h["destination_id"],
            vehicle_id=h["vehicle_id"],
            outcome=h["outcome"],
            failure_reason=h["failure_reason"],
            notes=h["driver_notes"],
            actual_cost=h["cost"],
            delivery_time=h["delivery_time"],
            timestamp=h["timestamp"],
            location=h["location"],
            evidence_added=h["evidence_tagged"],
            reliability_impact="+2.4% local confidence score boost" if h["outcome"] == "SUCCESS" else "Failure risk updated in database."
        ))

    # 6. Pools
    pools_data = [
        {
            "id": "POOL-2026-091",
            "corridor_name": "Green Valley Corridor (NH-26 -> Rampuram & Pathapatnam)",
            "primary_shipment_id": "RN-2026-8801",
            "secondary_shipment_id": "RN-2026-8804",
            "destination_a": "Rampuram Village Hub",
            "destination_b": "Pathapatnam Main Junction",
            "shared_corridor_km": 14.8,
            "time_window_overlap": "92%",
            "vehicle_capacity_before": "42%",
            "vehicle_capacity_after": "86%",
            "combined_weight_kg": 550.0,
            "vehicle_assigned_id": "VEH-MINI-01",
            "vehicle_assigned_name": "Tata Ace Gold 4x4 Mini Truck (AP-31-TX-9012)",
            "expected_loss_individual": 605.0,
            "expected_loss_pooled": 140.0,
            "total_savings": "$465 (76.8% reduction)",
            "status": "READY_FOR_DISPATCH",
            "compatibility_scores": {
                "routeOverlap": "96%",
                "timeCompatibility": "90%",
                "weightVolumeFit": "88%",
                "roadRiskSafety": "94%"
            },
        },
        {
            "id": "POOL-2026-092",
            "corridor_name": "Kothuru-Badangi Valley Pass Corridor",
            "primary_shipment_id": "RN-2026-8802",
            "secondary_shipment_id": "RN-2026-8809",
            "destination_a": "Kothuru Health Clinic",
            "destination_b": "Badangi Chilling Plant",
            "shared_corridor_km": 9.2,
            "time_window_overlap": "85%",
            "vehicle_capacity_before": "25%",
            "vehicle_capacity_after": "68%",
            "combined_weight_kg": 265.0,
            "vehicle_assigned_id": "VEH-VAN-02",
            "vehicle_assigned_name": "Maruti Eeco Cargo Van (AP-31-VN-5520)",
            "expected_loss_individual": 220.0,
            "expected_loss_pooled": 85.0,
            "total_savings": "$135 (61.3% reduction)",
            "status": "MATCH_SUGGESTED",
            "compatibility_scores": {
                "routeOverlap": "82%",
                "timeCompatibility": "85%",
                "weightVolumeFit": "92%",
                "roadRiskSafety": "88%"
            },
        }
    ]

    for p in pools_data:
        db.add(Pool(**p))

    db.commit()
    print("Database seeding completed successfully.")
